In [1]:
import torch
import numpy as np

In [2]:
#  任务1：创建一个指定形状的随机张量和全零张量
#   注意：一维的张量是中性的，没有行向量和列向量之分，既不是行向量也不是列向量。就是一个一维的张量
x = torch.rand(3, 4)    # 创建一个[0:1)的均匀分布的3乘4大小的随机张量
y = torch.ones(3, 4)    # 创建一个全为1的3乘4大小的张量
range = torch.arange(0, 5)
z = torch.zeros(3, 4)   # 创建一个全为0的3乘4大小的张量
m = torch.randn(3, 4)   # 创建一个3乘4大小的正态分布的张量
n = torch.arange(0, 12).reshape(3, 4)  #创建一个从0到11顺序排列的向量组并将其转成3乘4形状的矩阵
p = torch.tensor([1, 2, 3])
x, y, z, m, n, range, range.shape, p, p.shape

(tensor([[0.6954, 0.1318, 0.0294, 0.4051],
         [0.2180, 0.1494, 0.8483, 0.7179],
         [0.3097, 0.4650, 0.6082, 0.2002]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[ 0.5260, -0.9683, -1.5842,  1.0144],
         [-1.8951,  1.1087, -0.0298,  0.6353],
         [-1.4308,  2.2208, -0.2911, -1.0541]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([0, 1, 2, 3, 4]),
 torch.Size([5]),
 tensor([1, 2, 3]),
 torch.Size([3]))

In [3]:
a = torch.arange(12)
a, a.shape

(tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), torch.Size([12]))

In [4]:
#  任务2：练习张量的基本数学运算（加、减、乘、矩阵乘法 @）
'''有两种矩阵乘法，真正矩阵乘法和元素级乘法
（1） a @ b   第一个矩阵的行与第二个矩阵的列进行点积运算，与torch.matmul(a, b)一模一样
（2） torch.mm()  只支持两个二维矩阵的乘法，不支持批处理和广播
（3） a * b   将两个形状相同的矩阵中对应位置的元素进行相乘与torch.mul(a, b)一模一样
'''
'''
广播机制：
（1）维度兼容：从后往前比较它们的维度大小，在每个维度上，必须满足以下三个条件之一：
首先执行：如果两个张量的维度数量不同，那么在维度较少的那个张量的左侧补1，直到它们的维度数量相等。如(4,)会被补成(1,4)

a、它们的维度大小相等。指的是（3，4）和（3，4）这样维度大小才是相等的

b、其中一个张量的维度大小为 1。

c、其中一个张量不存在该维度。
注：矩阵乘法有点特殊，@运算时，只会对批次维度进行标准广播，对这个矩阵形状这最后两个维度不会进行广播，必须满足标准的矩阵乘法的要求

（2）自动扩展：如果满足兼容条件，运算结果的形状将取两个张量在该维度上的最大值。维度大小为 1 或者不存在的维度，会被自动扩展以匹配另一个张量的维度大小。
'''
tensor_rand = torch.rand(3, 4)
tensor_ones = torch.ones(3, 4)
board_tensor = torch.ones(4,)
mul_tensor = torch.arange(0, 4).reshape(1, 4)
mul_tensor1 = torch.arange(0, 4).reshape(4, 1)
tensor_arange = torch.arange(0,12).reshape(3,4)
tensor_rand + tensor_ones, tensor_ones - tensor_rand, tensor_ones + board_tensor   # 矩阵加法与减法，逐个矩阵元素互相加减

(tensor([[1.7517, 1.1540, 1.4614, 1.8343],
         [1.2264, 1.7247, 1.2970, 1.6116],
         [1.6321, 1.1393, 1.2886, 1.7816]]),
 tensor([[0.2483, 0.8460, 0.5386, 0.1657],
         [0.7736, 0.2753, 0.7030, 0.3884],
         [0.3679, 0.8607, 0.7114, 0.2184]]),
 tensor([[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]))

In [5]:
tensor_rand @ board_tensor,  tensor_ones @ mul_tensor1.float()   #这里做了一个处理将board_tensor从（4，）变成了（4，1）形状，是一个特例，而且结果也变成了一维torch.Size([3])，而不是torch.Size([3, 1])
#tensor_ones为整型数据，mul_tensor1为浮点型数据，PyTorch的矩阵乘法 (@) 操作要求两个张量的数据类型一致

(tensor([2.2013, 1.8598, 1.8415]),
 tensor([[6.],
         [6.],
         [6.]]))

In [6]:
tensor_rand @ board_tensor == tensor_rand @ (board_tensor.reshape(4, 1))    #这里也进行了广播，左边结果形状为torch.Size([3])，右边结果形状为torch.Size([3, 1])，左边先被补充成（1，3），然后两个分别进行广播

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True]])

In [7]:
(tensor_rand @ board_tensor).shape, (tensor_ones @ mul_tensor1.float()).shape, (tensor_rand @ (board_tensor.reshape(4, 1))).shape

(torch.Size([3]), torch.Size([3, 1]), torch.Size([3, 1]))

In [8]:
tensor_rand * tensor_ones, tensor_rand * board_tensor, tensor_rand * mul_tensor

(tensor([[0.7517, 0.1540, 0.4614, 0.8343],
         [0.2264, 0.7247, 0.2970, 0.6116],
         [0.6321, 0.1393, 0.2886, 0.7816]]),
 tensor([[0.7517, 0.1540, 0.4614, 0.8343],
         [0.2264, 0.7247, 0.2970, 0.6116],
         [0.6321, 0.1393, 0.2886, 0.7816]]),
 tensor([[0.0000, 0.1540, 0.9228, 2.5028],
         [0.0000, 0.7247, 0.5940, 1.8349],
         [0.0000, 0.1393, 0.5772, 2.3448]]))

In [9]:
# 任务3：练习张量的索引、切片、拼接 (torch.cat) 和堆叠 (torch.stack)
task3_tensor = torch.arange(0, 12).reshape(3, 4)
task3_tensor1 = torch.ones(3, 4)
task3_tensor2 = torch.zeros(1, 4)
sp = torch.tensor([])
task3_tensor[0], task3_tensor[-1], task3_tensor[:, 0], task3_tensor[:, -1], task3_tensor[..., -1]

(tensor([0, 1, 2, 3]),
 tensor([ 8,  9, 10, 11]),
 tensor([0, 4, 8]),
 tensor([ 3,  7, 11]),
 tensor([ 3,  7, 11]))

In [10]:
task3_tensor[0, -1]

tensor(3)

In [11]:
task3_tensor[:, 0] = 0    # 替换操作
task3_tensor

tensor([[ 0,  1,  2,  3],
        [ 0,  5,  6,  7],
        [ 0,  9, 10, 11]])

In [12]:
torch.cat((task3_tensor, task3_tensor), dim=0), torch.cat((task3_tensor, task3_tensor), dim=1)

(tensor([[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
         [ 0,  5,  6,  7,  0,  5,  6,  7],
         [ 0,  9, 10, 11,  0,  9, 10, 11]]))

In [13]:
torch.cat([task3_tensor, task3_tensor], dim=0), torch.cat((task3_tensor, task3_tensor), dim=0)

(tensor([[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11],
         [ 0,  1,  2,  3],
         [ 0,  5,  6,  7],
         [ 0,  9, 10, 11]]))

In [14]:
torch.cat((task3_tensor, task3_tensor2), dim=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 0.,  5.,  6.,  7.],
        [ 0.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.]])

In [15]:
torch.cat((task3_tensor, sp), dim=0).shape

torch.Size([3, 4])

In [16]:
'''
stack操作：dim=0	新增维度插入最前面	(2, 3, 4)	把整个矩阵作为单元进行堆叠，其中2为堆叠的张量的数量
          dim=1，新增维度插入第2个位置（3，2，4）    把每一行作为单元进行堆叠
          dim=2，新增维度插入第3个位置（3，4，2）    把每一个元素作为单元进行堆叠
'''
torch.stack((task3_tensor, task3_tensor), dim=0), torch.stack((task3_tensor, task3_tensor), dim=1), torch.stack((task3_tensor, task3_tensor), dim=2)        # stack操作中所有的向量形状必须一样

(tensor([[[ 0,  1,  2,  3],
          [ 0,  5,  6,  7],
          [ 0,  9, 10, 11]],
 
         [[ 0,  1,  2,  3],
          [ 0,  5,  6,  7],
          [ 0,  9, 10, 11]]]),
 tensor([[[ 0,  1,  2,  3],
          [ 0,  1,  2,  3]],
 
         [[ 0,  5,  6,  7],
          [ 0,  5,  6,  7]],
 
         [[ 0,  9, 10, 11],
          [ 0,  9, 10, 11]]]),
 tensor([[[ 0,  0],
          [ 1,  1],
          [ 2,  2],
          [ 3,  3]],
 
         [[ 0,  0],
          [ 5,  5],
          [ 6,  6],
          [ 7,  7]],
 
         [[ 0,  0],
          [ 9,  9],
          [10, 10],
          [11, 11]]]))

In [18]:
#任务4：练习张量的形状变换：view(), reshape(), squeeze(), unsqueeze()
x = torch.tensor([1, 2, 3])
print(x.shape)

torch.Size([3])


In [21]:
'''
unsqueeze 的作用是在指定位置插入一个大小为 1 的新维度。

语法: tensor.unsqueeze(dim) 或 torch.unsqueeze(tensor, dim)

dim: 你希望插入新维度的位置。
'''
y = x.unsqueeze(dim=1)
z = x.unsqueeze(dim=0)
print(y.shape, z.shape)

torch.Size([3, 1]) torch.Size([1, 3])


In [29]:
'''
squeeze 的作用是移除张量中所有或指定的大小为 1 的维度。

语法: tensor.squeeze(dim=None)

dim (可选):

如果不提供 dim，它会移除所有大小为 1 的维度。

如果提供了 dim，它只会在指定位置移除维度，前提是该维度的大小必须为 1。如果不是1，则什么也不做。
'''
h = torch.arange(12).reshape(1, 1, 12)
print(h, h.shape)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]]) torch.Size([1, 1, 12])


In [28]:
an1 = h.squeeze()
an2 = torch.squeeze(h, dim=1)
an3 = h.squeeze(dim=-1)
print(an1, an2.shape, an3.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]) torch.Size([1, 12]) torch.Size([1, 1, 12])


In [30]:
'''
torch.reshape(x,(a,b,c))或x.reshape((a,b,c)),将x转换成形状为a乘b乘c的张量。
torch.reshape(x,(-1,c)),将x转换成m乘c形状的张量，这里的-1为一个占位符，意思是确定了x的第二个维度为c，第一个维度torch帮我算出来
'''
origin_tensor = torch.arange(1,13).reshape(-1,6)
print(origin_tensor.shape)

torch.Size([2, 6])


In [32]:
y = torch.reshape(origin_tensor,(3,4))
print(y)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [65]:
grad = torch.tensor([[1.0,2,3],[4,5,6],[7,8,9]], requires_grad=True)
grad_b = torch.arange(4.0,requires_grad=True)
print(grad_b.shape, grad.shape, grad_b.grad)

torch.Size([4]) torch.Size([3, 3]) None


In [56]:
y = torch.dot(grad_b, grad_b) + 5
y


tensor(19., grad_fn=<AddBackward0>)

In [57]:
y.backward()
print(grad_b.grad)

tensor([0., 2., 4., 6.])


In [58]:
grad_b.grad == 2 * grad_b

tensor([True, True, True, True])

In [66]:
y1 = grad * grad
y1.sum().backward()
print(grad.grad)

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.],
        [14., 16., 18.]])
